# https://jekyllrb.com/docs/configuration/options/
#

#https://github.com/jekyll/jekyll/issues/3478
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

encoding: utf-8
incremental: true
lsi: true

url: https://mingster.github.io
#url: 'https://localhost:4000'
baseurl: ''
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title
#permalink: /blog/:year/:month/:title.html
permalink: /:title/
logo: 'assets/images/logo.png'
google_analytics: 'UA-255651-1'
disqus: 'mingster'
include: ['_pages', '.htaccess']
exclude: ["*.sh", "LICENSE", ".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json", "node_modules"]
keep_files: ["node_modules"]

#markdown: redcarpet
markdown: kramdown
highlights: rouge
timezone: Asia/Taipei
safe: false

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: mingster.com
tagline:
description:
about:

# Authors
authors:
  mingster:
    name: mingster
    display_name: mingster
    gravatar: e12a62479436fc70cc5696a146b2ae4e
    email: mingster.sai_at_gmail.com
    github: mingster
    twitter: mingster
    facebook: mingshentsai
    googleplus: +MingTsaigplus
    feedburner : mingster/github

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
